-   id: dart-format
    name: Format Dart Code
    entry: format
    language: script
    files: \.dart$

-   id: flutter-analyze
    name: Analyze Flutter Code
    entry: analyze
    language: script
    files: \.dart$
