-   id: dart-format
    name: Format Dart Code
    entry: run1
    language: script
    files: \.dart$
-   id: dart-analyze
    name: Analyze Dart Code
    entry: run2
    language: script
    files: \.dart$